### ISSUE TITLE
메인 화면에서 Swiper 스타일링이 갑자기 변경되는 문제..

### ISSUE THREAD

**Issue by DataCodeLiteracy** [super-1th-project-team/watcha-pedia-clone#27]
여러가지로 시도해보고 있다. 
현재 Swiper안에 있는 일부 요소들이 스타일 컴포넌트 적용이 안되고 있다. 그래서 직접 스타일을 적용해서 어느 정도 문제를 해결했지만
제대로 된 해결책이 아니라고 생각한다. 

이 부분에 대해서 팀원들과 이슈를 공유하고 같이 해결하고자 한다.

**Comment by DataCodeLiteracy** [comment]
Swiper 이미지의 높이 값을 %로 줘서 윈도우 크기에 반응하게 하려고 하다보니까 부모요소의 높이값이 정해져 있지 않아서 이미지의 크기가 들쭉 날쭉 한 거 같은데.. 특정 부모요소에서 높이값을 px단위로 주면 이미지의 문제는 해결되지만, 그건 윈도우 창의 크기에 따라 이미지의 높이가 변경되지 않기 때문에 적절한 해결책은 아닌 것 같아요.. 그래서 이 부분을 해결할 수 있는 걸 좀 더 알아봐야 할 것 같습니다.

**Comment by yeona23** [comment]
ratio로 비율을 지정하여 해결
